apiVersion: vmoperator.vmware.com/v1alpha4
kind: VirtualMachine
metadata:
  name: ben-test
spec:
  className:    best-effort-xsmall
  imageName:    vmi-4c48b6f40db2f6384
  storageClass: home-mgmt-cl01-optimal-datastore-default-policy-raid5
  bootstrap:
    cloudInit:
      cloudConfig: {}
